name: APK build and release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and release APK
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Decode Keystore File
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > app/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build APK
        env:
          KEYSTORE_FILE_PATH: keystore.jks
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Auto-generated release for tag ${{ github.ref_name }}.
          artifacts: "app/build/outputs/apk/release/*.apk"
          draft: false
          prerelease: false
